name: Watermelons are awesome

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        run: echo "Hello world!"
      - name: Get Node versions
        run: |
          node -v 
          npm -v
      - name: Python Commands
        run: |
          import platform
          print("Python says - Hello, world!")
          print(platform.processor())
        shell: python
  windows-world:
    runs-on: windows-latest
    needs: ["hello-world"]
    steps:
      - name: Show current working directory
        run: Get-Location
      - name: Directory-bash
        run: pwd
        shell: bash
